dist: trusty
sudo: required

language: c

env:
  - ELECTRON_CACHE=$HOME/.electron

matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

cache:
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.cache

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - libsecret-1-dev
      - icnsutils

install:
  - nvm install 6
  - npm install
  - sudo echo "deb http://us.archive.ubuntu.com/ubuntu/ xenial main restricted" >> /etc/apt/sources.list
  - sudo echo "deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates main restricted" >> /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get install snapcraft

script:
  - npm run release

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
