osx_image: xcode8.3
sudo: false
language: node_js
node_js: '8'
env:
- ELECTRON_CACHE=$HOME/.electron
matrix:
  include:
  - os: osx
cache:
  directories:
  - node_modules
  - "$HOME/Library/Caches/electron"
  - "$HOME/Library/Caches/electron-builder"
before_install:
- openssl aes-256-cbc -K $encrypted_8b56ae4b0315_key -iv $encrypted_8b56ae4b0315_iv
  -in apple.cer.enc -out apple.cer -d
install:
- npm install
script:
- npm run dist
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
