# See https://github.com/electron-userland/electron-builder/wiki/Publishing-Artifacts
# for the most up to date recommended .travis.yml
dist: trusty
sudo: false

language: node_js
node_js: "6"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - linux

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

addons:
  apt:
    packages:
      - libsecret-1-0
      - rpmbuild

install:
  - npm install

script:
  - npm run dist

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
