dist: trusty
sudo: required

language: c

env:
  - ELECTRON_CACHE=$HOME/.electron

matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

cache:
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.cache

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - libsecret-1-dev
      - icnsutils
      - snapd

install:
- nvm install 6
- npm install

script:
- npm run release

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
